version: '3'

services:

  # nginx
  __NAMESPACE__-mongo-__NODE_ID__-nginx:
    image: nginx:1-alpine
    container_name: __NAMESPACE__-mongo-__NODE_ID__-nginx

    ports:
      - "__NODE_MONGO_PORT__:__NODE_MONGO_PORT__" # mongo

    volumes:
      - ./cert:/cert:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/http.conf:/http.conf:ro
      - ./nginx/acl.conf:/acl.conf:ro

    environment:
      - ASM_MONGO_NGINX_EXPOSER_RESOLVER_COMMENT=${ASM_MONGO_NGINX_EXPOSER_RESOLVER_COMMENT:-#}
      - ASM_MONGO_NGINX_EXPOSER_RESOLVER_VALUE=${ASM_MONGO_NGINX_EXPOSER_RESOLVER_VALUE:-1.1.1.1 8.8.8.8 9.9.9.9 valid=300 ipv6=off}
      - ASM_MONGO_NGINX_EXPOSER_WORKER_PROCESSES=${ASM_MONGO_NGINX_EXPOSER_WORKER_PROCESSES:-auto}
      - ASM_MONGO_NGINX_EXPOSER_LOG_LEVEL=${ASM_MONGO_NGINX_EXPOSER_LOG_LEVEL:-warn}
      - ASM_MONGO_NGINX_EXPOSER_WORKER_CONNECTIONS=${ASM_MONGO_NGINX_EXPOSER_WORKER_CONNECTIONS:-4096}
      - ASM_MONGO_NGINX_EXPOSER_MONGO_PORT=__NODE_MONGO_PORT__
      - ASM_MONGO_NGINX_EXPOSER_MONGO_CONTAINER=__NAMESPACE__-mongo-__NODE_ID__

    logging:
      driver: "journald"
      options:
        tag: "APP=__NAMESPACE__-mongo-replica TYPE=nginx NODE_ID=__NODE_ID__ NGINX_STREAM_DOCKER_EXPOSER=1"

  # mongodb_exporter
  __NAMESPACE__-mongo__NODE_ID__-exporter:
    image: percona/mongodb_exporter:0.37
    container_name: __NAMESPACE__-mongo__NODE_ID__-exporter
    entrypoint: /mongodb_exporter --collector.diagnosticdata --collector.replicasetstatus --collector.dbstats --collector.topmetrics --collector.indexstats --collector.collstats --web.listen-address="0.0.0.0:__NODE_X_EXPORTER_PORT__" --mongodb.uri="mongodb://root_readonly:__ROOT_READONLY_PASSWORD__@__NAMESPACE__-mongo-__NODE_ID__.__DOMAIN__:__NODE_MONGO_PORT__/admin?tls=true&tlsCertificateKeyFile=/cert/server-combined.pem&tlsCAFile=/cert/ca.pem"
    restart: always
    ports:
      - 127.0.0.1:__NODE_X_EXPORTER_PORT__:__NODE_X_EXPORTER_PORT__
    volumes:
      - ./cert:/cert:ro

  # mongo
  __NAMESPACE__-mongo-__NODE_ID__:
    image: mongo:6.0
    container_name: __NAMESPACE__-mongo-__NODE_ID__
    hostname: __NAMESPACE__-mongo-__NODE_ID__.__DOMAIN__
    entrypoint: mongod --quiet --port __NODE_MONGO_PORT__ --bind_ip_all --auth --replSet __REPLICA_NAME__ --profile 1 --slowms 1000 --enableFreeMonitoring off --tlsMode requireTLS --tlsCAFile /cert/ca.pem --tlsCertificateKeyFile /cert/server-combined.pem --clusterAuthMode x509
    restart: always
    # ports:
    #   - __NODE_MONGO_PORT__:__NODE_MONGO_PORT__
    volumes:
      - ./scripts:/scripts:ro
      - ./cert:/cert:ro
      - ${BACKUP_PATH:-/tmp/backup}/__NAMESPACE__-mongo__NODE_ID__:/backup
      - ${DATA_PATH:-/tmp}/__NAMESPACE__-mongo__NODE_ID__:/data/db

    logging:
      driver: "journald"
      options:
        tag: "APP=__NAMESPACE__-mongo-replica TYPE=mongo NODE_ID=__NODE_ID__"
    # manually added ip host
    # extra_hosts:
    #   __NAMESPACE__-mongo-0.__DOMAIN__: 192.168.0.1
    #   __NAMESPACE__-mongo-1.__DOMAIN__: 192.168.0.2
    #   __NAMESPACE__-mongo-2.__DOMAIN__: 192.168.0.3
